### ISSUE TITLE
How to cite COVFEFE?

### ISSUE THREAD

**Issue by luckytoilet** [SPOClab-ca/COVFEFE#17]
I've used COVFEFE on one research paper and my thesis. In both cases I added a link to this repo in the footnote. Should we have a proper citation, for example, an arxiv paper or at least a DOI identifier?

**Comment by daniyall** [comment]
There is an accepted paper that should be out soon. I will update this issue and add a section for citing in the readme when it's out.

**Comment by daniyall** [comment]
Added citation section
