### ISSUE TITLE
Output Folder is empty

### ISSUE THREAD

**Issue by anandhperumal** [SPOClab-ca/COVFEFE#19]
Python command 

```
python covfefe.py -i input_data -o output_folder -p lex
```
and in my input folder there is only one file with following lines
```
Hi How are you
I'm good
```
and in my output folder it creates lexicosyntactics folder but nothing is there inside that folder.
Let me know if I'm missing anything

**Comment by luckytoilet** [comment]
This looks right to me. Are there any errors in the output when you run that command?

**Comment by anandhperumal** [comment]
Nope

**Comment by luckytoilet** [comment]
The only logs are output to stdout. Can you paste the output when you run the command?

**Comment by anandhperumal** [comment]
Sorry for the delay. There is nothing
![image](https://user-images.githubusercontent.com/12907396/67302297-ef21cc80-f4ad-11e9-88ca-f0cd566c635e.png)

**Comment by luckytoilet** [comment]
Does your input file have the extension `.txt`?

**Comment by daniyall** [comment]
+1 for checking the file extension. The fact that there were no warnings or progress bar makes me think that the file_finder didn't find any input files.

**Comment by anandhperumal** [comment]
@luckytoilet @daniyall  Thanks my file didn't have txt extension.
But now fixing that leads to me a new issue:
```
anandhpe_ualberta_ca@cpu8ram30:~/installs/GitHub/COVFEFE$ python3 covfefe.py -i input_data -o output_folder -p lex
  0%|                                                                                        | 0/1 [00:00<?, ?it/s]INFO:utils.logger:lexicosyntactic: Starting input_data/file1.txt
ERROR:utils.logger:lexicosyntactic: Failed with error 

===========================================================================
NLTK was unable to find the java file!
Use software specific configuration paramaters or set the JAVAHOME environment variable.
===========================================================================
INFO:utils.logger:lexicosyntactic: Done input_data/file1.txt -> output_folder/lexicosyntactic/file1.csv
100%|████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/it]
anandhpe_ualberta_ca@cpu8ram30:~/installs/GitHub/COVFEFE$ cd output_folder/lexicosyntactic/
anandhpe_ualberta_ca@cpu8ram30:~/installs/GitHub/COVFEFE/output_folder/lexicosyntactic$ ls
lu_parses  rst_output  stanford_parses
```
There is no file1.csv and all other folders are empty

**Comment by daniyall** [comment]
Do you have JAVA_HOME set?

Looks similar to https://github.com/nltk/nltk/issues/1476

**Comment by anandhperumal** [comment]
Hi @daniyall, Yes 
![image](https://user-images.githubusercontent.com/12907396/67601194-03293080-f731-11e9-86b4-5ea062d57117.png)

**Comment by daniyall** [comment]
This error is because one of the scripts used by the lex features still uses python2. But it looks like calling `python2` is not valid on your system. The immediate fix would be to create a link somewhere in your path that links `python2` to `python` or to change https://github.com/SPOClab-ca/COVFEFE/blob/7ee3233aaf51d5aeea0852fd0f64b77bc6c63bc8/utils/lexicosyntactic/syntactic_features.py#L31 to say `python` instead of `python2`.

**Comment by anandhperumal** [comment]
@daniyall Thanks for the input 
![image](https://user-images.githubusercontent.com/12907396/67611901-15b85f80-f75b-11e9-8151-5e8cd18c1b5e.png)

Now there is some other issue, what is receptiviti and  lexicosyntactic is supposed to be created as a ouput but then it's throwing error no such file or directory.

```
ERROR:utils.logger:lexicosyntactic: Failed with error [Errno 2] No such file or directory: '/home/anandhpe_ualberta_ca/installs/GitHub/COVFEFE/output_folder/lexicosyntactic/lu_parses/file1.txt'

```

**Comment by daniyall** [comment]
You can ignore the receptiviti error. The lexicosyntactic error looks a bit odd. Can you try deleting `output_folder` and running the pipeline again?

**Comment by anandhperumal** [comment]
@daniyall sorry for the delay 
tried deleting the output folder it didn't help
![image](https://user-images.githubusercontent.com/12907396/67710662-f7827780-f985-11e9-9b36-9eb0a14421a6.png)

**Comment by daniyall** [comment]
Is there anything inside the lu_parses folder?

**Comment by anandhperumal** [comment]
@daniyall  nothing is there inside lu_parser, Nevermind I tried in another server it's working fine.
I guess something is wrong with my env.
Thanks anyway

**Comment by kearnsdm** [comment]
I have the same problem as @anandhperumal exactly. I also made the change he made, and it caused the same problem for me. In the subprocess.call in syntactic_features.py, it mentions 'python2' and 'analyzeText.py' ... where is the latter coming from? Is it necessary to reference python2? I'm working in a virtual env per the ReadMe, but it's not working.

**Comment by daniyall** [comment]
I believe some of the dependencies require python2 which is why its being called. Are you using Windows, Mac or Linux?

**Comment by kearnsdm** [comment]
Windows... I have Python 2 installed but I am using a virtual environment bc COVFEFE wants old versions of programs . Not sure if that could raise an issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kearnsdm** [comment]
It looks like it is just analyzeText that is needed from Python 2. Is there an analogue in Python 3 or another way to handle this?
