### ISSUE TITLE
pywt no longer avaliable throught pip

### ISSUE THREAD

**Issue by superp0tat0** [SPOClab-ca/COVFEFE#23]
ERROR: Could not find a version that satisfies the requirement pywt==1.0.6 (from -r requirements.txt (line 28)) (from versions: none)
ERROR: No matching distribution found for pywt==1.0.6 (from -r requirements.txt (line 28))

**Comment by daniyall** [comment]
Looks like they renamed their package from pywt to pywavelets. I updated `requirements.txt`, let me know if this fixes it for you.

**Comment by superp0tat0** [comment]
Thank you for the quick response, the pip install works fine now.

**Comment by umairchanna57** [comment]
you can install 
pip install PyWavelets
