### ISSUE TITLE
wordnet_id not found

### ISSUE THREAD

**Issue by superp0tat0** [SPOClab-ca/COVFEFE#24]
In the install requirements, the nltk install package name has a name 'wordnet_id'. I think it is a typo as it should be 'wordet_ic'

**Comment by daniyall** [comment]
Does everything work if you change it to `wordnet_ic`? If so, you're welcome to make a pull request if you'd like. Otherwise, I'm happy to make the change.

**Comment by superp0tat0** [comment]
Yes, everything works after I change it to wordnet_ic. I could create a pull request.

**Comment by daniyall** [comment]
Thanks. I merged the pull request.
